package com.finley.flash.stream.dao;

import com.finley.flash.stream.domain.UserShareHour;
import com.finley.flash.stream.domain.UserShareHourExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserShareHourMapper {
    long countByExample(UserShareHourExample example);

    int deleteByExample(UserShareHourExample example);

    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("createTime") Date createTime);

    int insert(UserShareHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") UserShareHour record, @Param("selective") UserShareHour.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserShareHour selectOneByExample(UserShareHourExample example);

    List<UserShareHour> selectByExample(UserShareHourExample example);

    UserShareHour selectByPrimaryKey(@Param("userId") Long userId, @Param("createTime") Date createTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") UserShareHour record, @Param("example") UserShareHourExample example, @Param("selective") UserShareHour.Column ... selective);

    int updateByExample(@Param("record") UserShareHour record, @Param("example") UserShareHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") UserShareHour record, @Param("selective") UserShareHour.Column ... selective);

    int updateByPrimaryKey(UserShareHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<UserShareHour> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<UserShareHour> list, @Param("selective") UserShareHour.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(UserShareHour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") UserShareHour record, @Param("example") UserShareHourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") UserShareHour record, @Param("example") UserShareHourExample example, @Param("selective") UserShareHour.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") UserShareHour record, @Param("selective") UserShareHour.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<UserShareHour> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_hour
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<UserShareHour> list, @Param("selective") UserShareHour.Column ... selective);
}