package com.finley.flash.stream.dao;

import com.finley.flash.stream.domain.UserShare5Min;
import com.finley.flash.stream.domain.UserShare5MinExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserShare5MinMapper {
    long countByExample(UserShare5MinExample example);

    int deleteByExample(UserShare5MinExample example);

    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("createTime") Date createTime);

    int insert(UserShare5Min record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") UserShare5Min record, @Param("selective") UserShare5Min.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserShare5Min selectOneByExample(UserShare5MinExample example);

    List<UserShare5Min> selectByExample(UserShare5MinExample example);

    UserShare5Min selectByPrimaryKey(@Param("userId") Long userId, @Param("createTime") Date createTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") UserShare5Min record, @Param("example") UserShare5MinExample example, @Param("selective") UserShare5Min.Column ... selective);

    int updateByExample(@Param("record") UserShare5Min record, @Param("example") UserShare5MinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") UserShare5Min record, @Param("selective") UserShare5Min.Column ... selective);

    int updateByPrimaryKey(UserShare5Min record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<UserShare5Min> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<UserShare5Min> list, @Param("selective") UserShare5Min.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(UserShare5Min record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") UserShare5Min record, @Param("example") UserShare5MinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") UserShare5Min record, @Param("example") UserShare5MinExample example, @Param("selective") UserShare5Min.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") UserShare5Min record, @Param("selective") UserShare5Min.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<UserShare5Min> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_share_5min
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<UserShare5Min> list, @Param("selective") UserShare5Min.Column ... selective);
}